function f = dynamicFcn(x,u)
%dynamicFcn
%    F = dynamicFcn(x,u)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    07-Dec-2024 15:52:06


phi_t = x(1,:);
theta_t = x(2,:);
psi_t = x(3,:);
p_t = x(4,:);
q_t = x(5,:);
r_t = x(6,:);

% thrust = u(1,:);
tao_x = u(2,:);
tao_y = u(3,:);


% x_dot_t = x(7,:);
% y_dot_t = x(8,:);
% z_dot_t = x(9,:);
t2 = cos(phi_t);
t3 = cos(psi_t);
t4 = cos(theta_t);
t5 = sin(phi_t);
t6 = sin(psi_t);
t7 = sin(theta_t);
t8 = 1.0./t4;
f = [
    % x_dot_t;y_dot_t;z_dot_t;
    t8.*(p_t.*t4+q_t.*t5.*t7+r_t.*t2.*t7);q_t.*t2-r_t.*t5;t8.*(q_t.*t5+r_t.*t2);
    % thrust.*(t5.*t6+t2.*t3.*t7).*1.111111111111111e+3;thrust.*(t3.*t5-t2.*t6.*t7).*(-1.111111111111111e+3);t2.*t4.*thrust.*1.111111111111111e+3-9.81e+2./1.0e+2;
    tao_x.*1.818181818181818e+7-q_t.*r_t.*3.0;tao_y.*1.818181818181818e+7+p_t.*r_t.*3.0;0.0];
end
